### ISSUE TITLE
1.14 Version ?

### ISSUE THREAD

**Issue by mframbou** [gbl/RandomBlockPlacement#1]
Hey, it's not really an issue but I don't know where to post it ...

So all is in the title, could you make a 1.14 version (for fabric of course) ? It will be really helpful for me, thanks :D

**Comment by gbl** [comment]
I just uploaded a 1.14.4 version on curseforge, might take a few minutes to get approved. Tell me if that works for you.

**Comment by mframbou** [comment]
I just added it and ...


---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 07/03/20 23:07
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoSuchMethodError: io.github.cottonmc.clientcommands.ClientCommands.registerCommand(Ljava/util/function/Consumer;)V
		at de.guntram.mcmod.grid.Grid.registerLocalCommands(Grid.java:339)
		at de.guntram.mcmod.grid.Grid.onInitializeClient(Grid.java:59)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1434/420925675.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1713462256 bytes (1634 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.6+1.14.4
		clientcommands: Client Commands 0.2.1+1.14-pre5
		cloth: Cloth Events 0.6.0
		cloth-config2: Cloth Config v2 1.7.3
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		durabilityviewer: Giselbaers Durability Viewer 1.14-fabric0.2.7-1.5
		easiercrafting: EasierCrafting 1.14.4-fabric0.4.2-1.5.0
		easiervillagertrading: EasierVillagerTrading 1.14.4-fabric0.4.1-1.4
		fabric: Fabric API 0.4.2+build.246-1.14
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+28f8190f42
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+28f8190f42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.2+28f8190f42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+28f8190f42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.1+28f8190f42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-language-kotlin: Fabric Language Kotlin 1.3.31+build.4
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
		fabric-networking-v0: Fabric Networking (v0) 0.1.4+28f8190f42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.2+28f8190f42
		fabric-particles-v1: fabric-particles-v1 0.1.1+933c24c242
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.14+28f8190f42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
		fabricloader: Fabric Loader 0.7.8+build.184
		fiber2cloth: Fiber To Cloth 1.2.1
		flighthelper: FlightHelper 1.14-fabric0.2.7-1.2
		gbfabrictools: GBfabrictools 1.0.1
		grid: Grid 1.14-fabric0.2.7-1.4
		harvest: Harvest 1.0.4
		lightoverlay: Light Overlay 3.5
		litematica: Litematica 0.0.0-dev.20190720.191654
		malilib: MaLiLib 0.10.0-dev.20
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.8
		mousewheelie: Mouse Wheelie 1.4.0+1.14.4
		optifabric: Optifabric 0.7.1
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_slf4j_slf4j-simple: slf4j-simple 1.7.29
		org_zeroturnaround_zt-zip: zt-zip 1.13
		randomblockplacement: RandomBlockPlacement 1.14.4-fabric0.4.1-1.0
		removerecipebook: Remove Recipe Book 1.1
		roughlyenoughitems: Roughly Enough Items 3.2.8+build.51
		stepup: StepUp 11.14-fabric0.2.7-1.0.2
		tweed: Tweed API 2.2.8
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.16
		worldtime: WorldTime 1.14.4-fabric0.4.1-1.1
	Launched Version: fabric-loader-0.7.8+build.184-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by gbl** [comment]
This looks like you're still on the original version of Grid. Nice to see you're using my other mods as well :) But that old version is incompatible with newer mods that add commands to the game. Try this one: https://www.curseforge.com/minecraft/mc-mods/grid/files/2705903

**Comment by mframbou** [comment]
Oh ok thanks ! I'm trying now

**Comment by mframbou** [comment]
Mhhh I still got an error


---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 08/03/20 00:35
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint client!
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:153)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:220)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:41)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: io/github/cottonmc/clientcommands/ClientCommandPlugin
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:100)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:92)
		at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:143)
		... 14 more
	Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.clientcommands.ClientCommandPlugin
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:153)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:220)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:41)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1577064312 bytes (1504 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.6+1.14.4
		cloth: Cloth Events 0.6.0
		cloth-config2: Cloth Config v2 1.7.3
		durabilityviewer: Giselbaers Durability Viewer 1.14-fabric0.2.7-1.5
		easiercrafting: EasierCrafting 1.14.4-fabric0.4.2-1.5.0
		easiervillagertrading: EasierVillagerTrading 1.14.4-fabric0.4.1-1.4
		fabric: Fabric API 0.4.2+build.246-1.14
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+28f8190f42
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+28f8190f42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.2+28f8190f42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+28f8190f42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.1+28f8190f42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-language-kotlin: Fabric Language Kotlin 1.3.31+build.4
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
		fabric-networking-v0: Fabric Networking (v0) 0.1.4+28f8190f42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.2+28f8190f42
		fabric-particles-v1: fabric-particles-v1 0.1.1+933c24c242
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.14+28f8190f42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
		fabricloader: Fabric Loader 0.7.8+build.184
		fiber2cloth: Fiber To Cloth 1.2.1
		flighthelper: FlightHelper 1.14-fabric0.2.7-1.2
		gbfabrictools: GBfabrictools 1.0.1
		grid: Grid 1.14-fabric0.2.7-1.4.1
		harvest: Harvest 1.0.4
		lightoverlay: Light Overlay 3.5
		litematica: Litematica 0.0.0-dev.20190720.191654
		malilib: MaLiLib 0.10.0-dev.20
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.8
		mousewheelie: Mouse Wheelie 1.4.0+1.14.4
		optifabric: Optifabric 0.7.1
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_slf4j_slf4j-simple: slf4j-simple 1.7.29
		org_zeroturnaround_zt-zip: zt-zip 1.13
		removerecipebook: Remove Recipe Book 1.1
		roughlyenoughitems: Roughly Enough Items 3.2.8+build.51
		stepup: StepUp 11.14-fabric0.2.7-1.0.2
		tweed: Tweed API 2.2.8
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.16
		worldtime: WorldTime 1.14.4-fabric0.4.1-1.1
	Launched Version: fabric-loader-0.7.8+build.184-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by mframbou** [comment]
(not the same)

**Comment by mframbou** [comment]
And theres this in popup message, idk if that helps 

Error: net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint client!

**Comment by gbl** [comment]
Erm, I can't see RandomBlockPlacement in that second list .. the special version of Grid you downloaded *needs* some other mod that has the client command handler. Guess you updated grid without re-enabling RandomBlockPlacement?

**Comment by mframbou** [comment]
Oh sry, I was sure that I got it, maybe I was to tired ^^ thanks :D

**Comment by mframbou** [comment]
Yeah it works now 😄

**Comment by mframbou** [comment]
Perfect, exactly what I needed
