### ISSUE TITLE
Crash when i try to activate this mod

### ISSUE THREAD

**Issue by IZeeXeS** [gbl/RandomBlockPlacement#4]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 17.08.2021, 19:44
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_7353(net.minecraft.class_2561, boolean)" because "net.minecraft.class_310.method_1551().field_1724" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at de.guntram.mcmod.randomblockplacement.RandomBlockPlacement.setActive(RandomBlockPlacement.java:82)
	at de.guntram.mcmod.randomblockplacement.RandomBlockPlacement.processKeyBinds(RandomBlockPlacement.java:57)
	at de.guntram.mcmod.randomblockplacement.RandomBlockPlacement.lambda$setKeyBindings$0(RandomBlockPlacement.java:49)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$cbb000$onEndTick(MinecraftClient:17573)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1806)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1081)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.MinecraftClient.handler$bnj000$afterCrashHandled(MinecraftClient:16591)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:752)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.guntram.mcmod.randomblockplacement.RandomBlockPlacement.setActive(RandomBlockPlacement.java:82)
	at de.guntram.mcmod.randomblockplacement.RandomBlockPlacement.processKeyBinds(RandomBlockPlacement.java:57)
	at de.guntram.mcmod.randomblockplacement.RandomBlockPlacement.lambda$setKeyBindings$0(RandomBlockPlacement.java:49)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Invisible armor_v2.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bnj000$onCrash(class_310.java:16599)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.class_310.handler$bnj000$afterCrashHandled(class_310.java:16591)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 846583064 bytes (807 MiB) / 1509949440 bytes (1440 MiB) up to 3254779904 bytes (3104 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD E-300 APU with Radeon(tm) HD Graphics
	Identifier: AuthenticAMD Family 20 Model 2 Stepping 0
	Microarchitecture: Bobcat
	Frequency (GHz): 1,30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: AMD Radeon HD 6310 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 384,00
	Graphics card #0 deviceId: 0x9802
	Graphics card #0 versionInfo: DriverVersion=15.200.1062.1004
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,33
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 7370,40
	Virtual memory used (MB): 3860,60
	Swap memory total (MB): 3684,29
	Swap memory used (MB): 543,31
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=1 -XX:ParallelGCThreads=2 -Xmx3096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		advancedchat: AdvancedChat 3.3.1-1.17
		advancementinfo: AdvancementInfo 1.17.1-fabric0.36.1-1.2.1
		amecs: Amecs 1.3.4+mc.1.17
		amecsapi: Amecs API 1.1.5+mc21w16a
		annotateddi: Annotated DI 2.0.2+1.17.1
		aopalliance_aopalliance: aopalliance 1.0
		architectury: Architectury 2.1.20
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterpingdisplay: Better Ping Display 1.1
		betterthirdperson: Better Third Person 1.5.0
		clickthrough: ClickThrough 1.17.1-fabric0.36.1-0.4
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_google_inject_guice: guice 5.0.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		crowdin-translate: CrowdinTranslate 1.3+1.17
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		dontbreakme: Don't Mine Me 1.0
		durabilityviewer: Giselbaers Durability Viewer 1.17.1-fabric0.36.1-1.10.1
		dynmus: Dynamic Music 1.3.1
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		fancymenu: FancyMenu 2.2.2
		fiber: fiber 0.23.0-2
		fireplacelib: Fireplace Lib 5.0.1+1.17.1
		firstperson: FirstpersonModel 2.0.2
		flighthelper: FlightHelper 1.17.1-fabric0.36.1-1.2.1
		fpsreducer: FPS Reducer 1.23.1-mc1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		grid: Grid 1.17.1-fabric0.36.1-1.6.5
		horseinfo: Horse Info 0.3.0-1.17
		indium: Indium 1.0.0+rev.beb4972
		inventory_control_tweaks: Inventory Control Tweaks 1.3.8+MC1.17-1.17.1
		inventoryhud: Inventory HUD + 3.3.2
		inventoryprofilesnext: Inventory Profiles Next 0.8.6
		invtemplates: Inventory Templates 1.1.1
		itemmodelfix: Item Model Fix 1.0.2+1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		javax_inject_javax_inject: javax.inject 1
		konkrete: Konkrete 1.2.3
		krypton: Krypton 0.1.4
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lightoverlay: Light Overlay 6.1.0
		litematica: Litematica 0.0.0-dev.20210713.103711
		lithium: Lithium 0.7.3
		malilib: MaLiLib 0.10.0-dev.24
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.4
		moremcmeta: MoreMcmeta 1.17.1-3.0.0
		multiconnect: MultiConnect 1.4.6
		multiconnect-api: MultiConnect API 1.4.6
		nmuk: No More Useless Keys 1.0.1+mc1.17
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_yaml_snakeyaml: snakeyaml 1.29
		ostoverhaul: Ost Overhaul 0.1
		perspectivemod: Perspective Mod Redux 0.0.5_01
		pistorder: Pistorder 1.4.2
		randomblockplacement: RandomBlockPlacement 1.17.1-fabric0.36.1-1.1.1
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		skinshine: Skin Shine 1.1.9
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		spruceui: SpruceUI 3.2.0+1.17
		stendhal: Stendhal 1.2.0RC5-1.17
		textbook: Textbook 2.0.0+1.17.1
		transliterationlib: TRansliterationLib 1.1.0
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		tweakmyclient: TweakMyClient 1.1.8+build.24
		viafabric: ViaFabric 0.4.3+204-main
		viafabric-mc117: ViaFabric for 1.17 0.4.3+204-main
		viaversion: ViaVersion 4.0.2-SNAPSHOT
		voxelmap: VoxelMap 1.10.15
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
		wthit: wthit 3.8.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 6310 Graphics GL version 3.2.13399 Core Profile Forward-Compatible Context 15.200.1062.1004, ATI Technologies Inc.
	Window size: 1366x716
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/Invisible armor_v2.zip
	Current Language: Русский (Россия)
	CPU: 2x AMD E-300 APU with Radeon(tm) HD Graphics
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1), RandomBlockPlacement (randomblockplacement)

**Comment by gbl** [comment]
Thanks for the report!

The crash comes from the system trying to send a message to the player because the R key was pressed, when there's no player (yet), i.e. you just entered your world. 

This shouldn't be able to happen, and I have a suspicion the underlying error is something else, because of these lines in the crash log:

```
at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
at net.minecraft.client.MinecraftClient.handler$bnj000$afterCrashHandled(MinecraftClient:16591)
at net.minecraft.client.MinecraftClient.run(MinecraftClient:752)
```
where line 752, in the MC code, gets called when the client runs out of memory. So it might be that something else already went wrong earlier, and the randomblockplacement crash is just a follow-up error of that.

Anyway, I just published version 1.1.2 to CF and Modrinth, which does an extra check to avoid crashing in this case (pressing the key when there's no player yet). If installing that version just moves your crash to a different mod, maybe you need to increase your available memory. This is a bit inconsistent as Java has 3 GB which should be plenty.
